name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Setup API
        env:
          API_USER: ${{ secrets.API_USER }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: |
          cp ./packages/api/.env.ci ./packages/api/.env
          cp ./packages/api/db.dump.json ./packages/api/db.json

      - name: Setup website
        env:
          WEBSITE_ADMIN_USER: ${{ secrets.WEBSITE_ADMIN_USER }}
          WEBSITE_ADMIN_PASSWORD: ${{ secrets.WEBSITE_ADMIN_PASSWORD }}
          WEBSITE_API_USER: ${{ secrets.WEBSITE_API_USER }}
          WEBSITE_API_PASSWORD: ${{ secrets.WEBSITE_API_PASSWORD }}
        run: |
          cp ./packages/website/.env.ci ./packages/website/.env
          npm run assets:build -w packages/website

      - name: Start servers
        run: npm start &

      - name: Run tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npx percy exec -- npm test -w packages/website
